[package]
name = "os"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.5.0"
nvml-wrapper = "0.10.0"
serde = { version = "1.0.203", features = ["serde_derive"] }
sysinfo = "0.30.12"

